name: Step 2 - Open A Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_3_FILE: ".github/steps/3-merge-pr.md"
  TEMPLATES_REPOSITORY: "lufomatics/reusables"

jobs:
  find-workshop-issue:
    name: Find the Workshop Issue
    uses: lufomatics/reusables/.github/workflows/find-workshop-issue.yaml@v0.1.0
    with:
      issue-title-text: 'Workshop'  # Adjust if your workshop issue has a different title text

  check-work:
    name: Check Step Work
    runs-on: ubuntu-latest
    needs: [find-workshop-issue]
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify Step 2
        run: |
          gh issue comment ${{ needs.find-workshop-issue.outputs.issue-url }} \
            --body "Pull Request criado? Ótimo! Assim que estiver pronto, partiremos pro merge."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-next-step-content:
    name: Post Next Step
    runs-on: ubuntu-latest
    needs: [check-work, find-workshop-issue]
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEMPLATES_REPOSITORY }}
          path: ${{ format('.{0}', env.TEMPLATES_REPOSITORY) }}
          ref: v0.1.0

      - name: Comment - Step 3 instructions
        run: |
          gh issue comment ${{ needs.find-workshop-issue.outputs.issue-url }} \
            --body-file ${{ env.STEP_3_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current workflow and enable next one
        run: |
          gh workflow enable "Step 3 - Merge Your Pull Request"
          gh workflow disable "Step 2 - Open A Pull Request"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}