name: Step 3 - Merge Your Pull Request

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write
  issues: write
  actions: write

env:
  TEMPLATES_REPOSITORY: "lufomatics/reusables"

jobs:
  find-workshop-issue:
    name: Find the Workshop Issue
    uses: lufomatics/reusables/.github/workflows/find-workshop-issue.yaml@v0.1.0
    with:
      issue-title-text: 'Workshop'  # Adjust if your workshop issue has a different title text

  check-work:
    name: Check Step Work
    runs-on: ubuntu-latest
    needs: [find-workshop-issue]
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Confirm Merge
        if: github.event.pull_request.merged == true
        run: |
          gh issue comment ${{ needs.find-workshop-issue.outputs.issue-url }} \
            --body "Parabéns! Seu Pull Request foi mergeado com sucesso."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  close-workshop-issue:
    name: Close Workshop Issue
    runs-on: ubuntu-latest
    needs: [check-work, find-workshop-issue]
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment final
        run: |
          gh issue comment ${{ needs.find-workshop-issue.outputs.issue-url }} \
            --body "Este workshop foi concluído! Todas as configurações estão prontas para uso."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        run: |
          gh issue close ${{ needs.find-workshop-issue.outputs.issue-url }} --comment "Workshop finalizado."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}